# ============================================
# FAEP Academy Ecosystem Structure Creator
# Sprint 19
# ============================================

$dirs = @(

    # Academy Ecosystem
    "academy_ecosystem",

    "academy_ecosystem/question_banks",
    "academy_ecosystem/question_banks/qai",
    "academy_ecosystem/question_banks/qagi",
    "academy_ecosystem/question_banks/qasi",
    "academy_ecosystem/question_banks/ftqc",
    "academy_ecosystem/question_banks/digital_twins",
    "academy_ecosystem/question_banks/faep",
    "academy_ecosystem/question_banks/systems_engineering",
    "academy_ecosystem/question_banks/software_engineering",
    "academy_ecosystem/question_banks/cloud40",

    # Interview Preparation
    "academy_ecosystem/interview_preparation",
    "academy_ecosystem/interview_preparation/students",
    "academy_ecosystem/interview_preparation/engineers",
    "academy_ecosystem/interview_preparation/researchers",
    "academy_ecosystem/interview_preparation/architects",
    "academy_ecosystem/interview_preparation/scientists",
    "academy_ecosystem/interview_preparation/entrepreneurs",
    "academy_ecosystem/interview_preparation/investors",
    "academy_ecosystem/interview_preparation/franchise_partners",

    # Projects
    "academy_ecosystem/project_ideas",
    "academy_ecosystem/project_ideas/student_projects",
    "academy_ecosystem/project_ideas/engineering_projects",
    "academy_ecosystem/project_ideas/research_projects",
    "academy_ecosystem/project_ideas/startup_projects",
    "academy_ecosystem/project_ideas/capstone_projects",

    # Startup Foundry
    "academy_ecosystem/startup_foundry",
    "academy_ecosystem/startup_foundry/startup_ideas",
    "academy_ecosystem/startup_foundry/business_models",
    "academy_ecosystem/startup_foundry/validation",
    "academy_ecosystem/startup_foundry/incubation",
    "academy_ecosystem/startup_foundry/acceleration",
    "academy_ecosystem/startup_foundry/investor_readiness",

    # Franchise Ecosystem
    "academy_ecosystem/franchise_ecosystem",
    "academy_ecosystem/franchise_ecosystem/franchise_models",
    "academy_ecosystem/franchise_ecosystem/franchise_operations",
    "academy_ecosystem/franchise_ecosystem/partner_onboarding",
    "academy_ecosystem/franchise_ecosystem/regional_campuses",
    "academy_ecosystem/franchise_ecosystem/certification",

    # Onboarding
    "academy_ecosystem/onboarding",
    "academy_ecosystem/onboarding/students",
    "academy_ecosystem/onboarding/software_engineers",
    "academy_ecosystem/onboarding/systems_engineers",
    "academy_ecosystem/onboarding/researchers",
    "academy_ecosystem/onboarding/scientists",
    "academy_ecosystem/onboarding/entrepreneurs",
    "academy_ecosystem/onboarding/investors",
    "academy_ecosystem/onboarding/franchisees",
    "academy_ecosystem/onboarding/universities",
    "academy_ecosystem/onboarding/enterprises",

    # Expert Guidance
    "academy_ecosystem/expert_guidance",
    "academy_ecosystem/expert_guidance/qai",
    "academy_ecosystem/expert_guidance/ftqc",
    "academy_ecosystem/expert_guidance/digital_twins",
    "academy_ecosystem/expert_guidance/startups",
    "academy_ecosystem/expert_guidance/investment",
    "academy_ecosystem/expert_guidance/research",
    "academy_ecosystem/expert_guidance/careers",
    "academy_ecosystem/expert_guidance/governance",

    # Labs Extension
    "labs/academy",
    "labs/academy/beginner",
    "labs/academy/intermediate",
    "labs/academy/advanced",
    "labs/academy/research",
    "labs/academy/capstone",

    # Research Extension
    "research_intelligence/research_opportunities",
    "research_intelligence/research_opportunities/qai",
    "research_intelligence/research_opportunities/ftqc",
    "research_intelligence/research_opportunities/digital_twins",
    "research_intelligence/research_opportunities/world_models",
    "research_intelligence/research_opportunities/governance",
    "research_intelligence/research_opportunities/human_sovereignty",
    "research_intelligence/research_opportunities/future_systems",

    # FAEP Framework Extensions
    "faep/frameworks",
    "faep/frameworks/academy",
    "faep/frameworks/governance",
    "faep/frameworks/innovation",
    "faep/frameworks/operations",
    "faep/frameworks/engineering",
    "faep/frameworks/research",
    "faep/frameworks/startup"
)

Write-Host ""
Write-Host "Creating directories..."
Write-Host ""

foreach ($dir in $dirs)
{
    if (!(Test-Path $dir))
    {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "[Created] $dir"
    }

    $readme = Join-Path $dir "README.md"

    if (!(Test-Path $readme))
    {
        @"
# $(Split-Path $dir -Leaf)

Generated by FAEP Academy Structure Creator.

## Purpose

TODO

## Contents

TODO

"@ | Out-File $readme -Encoding UTF8
    }
}

# Root Academy Files

$rootFiles = @(
    "academy_ecosystem/academy_master_catalog.md",
    "academy_ecosystem/learning_paths.md",
    "academy_ecosystem/certification_paths.md",
    "academy_ecosystem/onboarding_guide.md"
)

foreach ($file in $rootFiles)
{
    if (!(Test-Path $file))
    {
        "# $(Split-Path $file -Leaf)" | Out-File $file -Encoding UTF8
        Write-Host "[Created] $file"
    }
}

Write-Host ""
Write-Host "======================================"
Write-Host "FAEP Academy Structure Created"
Write-Host "======================================"